[assign]

[relabel]
allow-unauthenticated = [
    "S-*", "A-*", "Edition-*", "bug", "enhancement", "question",
]

[shortcut]

[merge-conflicts]
remove = []
add = ["S-waiting-on-author"]
unless = ["S-blocked", "S-waiting-on-review"]

[autolabel."S-waiting-on-review"]
new_pr = true

[review-submitted]
reviewed_label = "S-waiting-on-author"
review_labels = ["S-waiting-on-review"]

[review-requested]
remove_labels = ["S-waiting-on-author"]
add_labels = ["S-waiting-on-review"]
