[package]
name = "tendril"
version = "0.2.4"
authors = ["Keegan McAllister <mcallister.keegan@gmail.com>",
           "Simon Sapin <simon.sapin@exyr.org>",
           "Chris Morgan <me@chrismorgan.info>"]
repository = "https://github.com/servo/tendril"
readme = "README.md"
license = "MIT/Apache-2.0"
description = "Compact buffer/string type for zero-copy parsing"

[dependencies]
mac = "0"
encoding = "0"
futf = "0.1.1"
utf-8 = "0.6"

[dev-dependencies]
rand = "0"

[features]
unstable = []
