[package]
name = "database"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2021"

[dependencies]
hashbrown = { version = "0.14", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
rusqlite = { version = "0.28", features = ["bundled"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "runtime"] }
anyhow = "1"
async-trait = "0.1"
tokio = { version = "1.6", features = ["sync", "macros"] }
intern = { path = "../intern" }
chrono = { version = "0.4.38", features = ["serde"] }
reqwest = { version = "0.11", features = ["blocking"] }
postgres-native-tls = "0.5"
native-tls = "0.2"
lazy_static = "1"
env_logger = "0.10"
futures-util = "0.3.5"
log = "0.4"
bytes = "1"
csv = "1"
clap = { version = "4.1", features = ["cargo"] }
x509-cert = { version = "0.2.5", features = ["pem"] }
