[package]
name = "image"
version = "0.10.3"
license = "MIT"
description = "Imaging library written in Rust. Provides basic filters and decoders for the most common image formats."
authors = [
    "ccgn",
    "bvssvni <bvssvni@gmail.com>",
    "nwin",
    "TyOverby <ty@pre-alpha.com>"]
readme = "README.md"
documentation = "http://www.piston.rs/image/image/index.html"
repository = "https://github.com/PistonDevelopers/image.git"
homepage = "https://github.com/PistonDevelopers/image"
exclude = [
    "src/png/testdata/*",
    "examples/*",
    "tests/*",
]
[lib]
name = "image"
path = "./src/lib.rs"

[dependencies]
byteorder = "0.5.1"
num-iter = "0.1.32"
num-rational = "0.1.32"
num-traits = "0.1.32"
enum_primitive = "0.1.0"
glob = "0.2.10"

[dependencies.gif]
version = "0.9"
optional = true

[dependencies.jpeg-decoder]
version = "0.1"
optional = true

[dependencies.png]
version = "0.5"
optional = true

[dependencies.scoped_threadpool]
version = "0.1"
optional = true

[dev-dependencies]
num-complex = "0.1.32"

[features]
default = ["gif_codec", "jpeg", "ico", "png_codec", "ppm", "tga", "tiff", "webp", "bmp", "hdr"]

gif_codec = ["gif"]
ico = ["bmp", "png_codec"]
jpeg = ["jpeg-decoder"]
png_codec = ["png"]
ppm = []
tga = []
tiff = []
webp = []
bmp = []
hdr = ["scoped_threadpool"]

[workspace]