[package]
name = "futures"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["futures", "async", "future"]
repository = "https://github.com/alexcrichton/futures-rs"
homepage = "https://github.com/alexcrichton/futures-rs"
documentation = "http://alexcrichton.com/futures-rs/futures/"
description = """
An implementation of futures and streams featuring zero allocations,
composability, and iterator-like interfaces.
"""

[dependencies]
log = "0.3"

[replace."openssl:0.7.14"]
git = "https://github.com/sfackler/rust-openssl"
branch = "breaks"

[workspace]