[package]
name = "svg-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
benchlib = { path = "../../benchlib", features = ["compression"] }
resvg = "0.34.1"

[workspace]
