[package]
name = "hashmap-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
benchlib = { path = "../../benchlib" }
hashbrown = { version = "0.13.2" }
fxhash = "0.2.1"

[workspace]
